//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hymax.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResourcesFA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResourcesFA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hymax.Localization.AppResourcesFA", typeof(AppResourcesFA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellLogin.
        /// </summary>
        internal static string ActivityHeaderPageTitle {
            get {
                return ResourceManager.GetString("ActivityHeaderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity from.
        /// </summary>
        internal static string ActivityPageTitle {
            get {
                return ResourceManager.GetString("ActivityPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNNING.
        /// </summary>
        internal static string ActivityTypeRunning {
            get {
                return ResourceManager.GetString("ActivityTypeRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وضعیت:.
        /// </summary>
        internal static string CarDateLabel {
            get {
                return ResourceManager.GetString("CarDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سویچ باز است.
        /// </summary>
        internal static string CarStatusOpen {
            get {
                return ResourceManager.GetString("CarStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کد.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل خود را وارد کنید.
        /// </summary>
        internal static string LoginDetails {
            get {
                return ResourceManager.GetString("LoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        internal static string LoginEntry {
            get {
                return ResourceManager.GetString("LoginEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به اپلیکیشن HY MAX خوش آمدید.
        /// </summary>
        internal static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string LoginVerifyButton {
            get {
                return ResourceManager.GetString("LoginVerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ۶ رقمی به شماره شما پیامک شد.
        /// </summary>
        internal static string LoginVerifyDetails {
            get {
                return ResourceManager.GetString("LoginVerifyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسالی را وارد کنید.
        /// </summary>
        internal static string LoginVerifyHeader {
            get {
                return ResourceManager.GetString("LoginVerifyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامکی دریافت نکردید؟.
        /// </summary>
        internal static string LoginVerifySendSMS {
            get {
                return ResourceManager.GetString("LoginVerifySendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مجدد پیامک.
        /// </summary>
        internal static string LoginVerifySendSMSButton {
            get {
                return ResourceManager.GetString("LoginVerifySendSMSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اثر انگشت خود را وارد کنید.
        /// </summary>
        internal static string PutFinger {
            get {
                return ResourceManager.GetString("PutFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اثر انگشت خود را وارد کنید.
        /// </summary>
        internal static string PutFingerHeader {
            get {
                return ResourceManager.GetString("PutFingerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش امنیت ورود به نرم افزار را انتخاب کنید.
        /// </summary>
        internal static string SecureDetails {
            get {
                return ResourceManager.GetString("SecureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اثر انگشت.
        /// </summary>
        internal static string SecureFinger {
            get {
                return ResourceManager.GetString("SecureFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امنیت ورود به HY MAX.
        /// </summary>
        internal static string SecureHeader {
            get {
                return ResourceManager.GetString("SecureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        internal static string SecurePassword {
            get {
                return ResourceManager.GetString("SecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگو.
        /// </summary>
        internal static string SecurePattern {
            get {
                return ResourceManager.GetString("SecurePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پین کد.
        /// </summary>
        internal static string SecurePin {
            get {
                return ResourceManager.GetString("SecurePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اثر انگشت را وارد کنید.
        /// </summary>
        internal static string SetSecureDetailsFingerPrint {
            get {
                return ResourceManager.GetString("SetSecureDetailsFingerPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا رمز عبور را وارد کنید.
        /// </summary>
        internal static string SetSecureDetailsPassword {
            get {
                return ResourceManager.GetString("SetSecureDetailsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا الگو مورد نظر را انتخاب کنید.
        /// </summary>
        internal static string SetSecureDetailsPattern {
            get {
                return ResourceManager.GetString("SetSecureDetailsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا پین کد را وارد کنید.
        /// </summary>
        internal static string SetSecureDetailsPin {
            get {
                return ResourceManager.GetString("SetSecureDetailsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودروتو هروقت و هرجا کنترل کن.
        /// </summary>
        internal static string Welcome1Description {
            get {
                return ResourceManager.GetString("Welcome1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودروتو کنترل کن.
        /// </summary>
        internal static string Welcome1Header {
            get {
                return ResourceManager.GetString("Welcome1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر تعداد خوردویی که دوس داری رو ردیابی کن.
        /// </summary>
        internal static string Welcome2Description {
            get {
                return ResourceManager.GetString("Welcome2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی از ردیابی چندین خودرو.
        /// </summary>
        internal static string Welcome2Header {
            get {
                return ResourceManager.GetString("Welcome2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در لحظه خودروتو ردیابی کن.
        /// </summary>
        internal static string Welcome3Description {
            get {
                return ResourceManager.GetString("Welcome3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیابی آنلاین.
        /// </summary>
        internal static string Welcome3Header {
            get {
                return ResourceManager.GetString("Welcome3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        internal static string WelcomeButton {
            get {
                return ResourceManager.GetString("WelcomeButton", resourceCulture);
            }
        }
    }
}
