//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hymax.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResourcesFA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResourcesFA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hymax.Localization.AppResourcesFA", typeof(AppResourcesFA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellLogin.
        /// </summary>
        internal static string ActivityHeaderPageTitle {
            get {
                return ResourceManager.GetString("ActivityHeaderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity from.
        /// </summary>
        internal static string ActivityPageTitle {
            get {
                return ResourceManager.GetString("ActivityPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNNING.
        /// </summary>
        internal static string ActivityTypeRunning {
            get {
                return ResourceManager.GetString("ActivityTypeRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودرو یاب.
        /// </summary>
        internal static string AdvanceAlarmMenu {
            get {
                return ResourceManager.GetString("AdvanceAlarmMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قفل کودک.
        /// </summary>
        internal static string AdvanceChildLockMenu {
            get {
                return ResourceManager.GetString("AdvanceChildLockMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن درب خودرو.
        /// </summary>
        internal static string AdvanceCloseDoorMenu {
            get {
                return ResourceManager.GetString("AdvanceCloseDoorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن پنجره ها.
        /// </summary>
        internal static string AdvanceCloseWindowsMenu {
            get {
                return ResourceManager.GetString("AdvanceCloseWindowsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف فوری.
        /// </summary>
        internal static string AdvanceForceStopMenu {
            get {
                return ResourceManager.GetString("AdvanceForceStopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن درب خودرو.
        /// </summary>
        internal static string AdvanceOpenDoorMenu {
            get {
                return ResourceManager.GetString("AdvanceOpenDoorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن صندوق عقب.
        /// </summary>
        internal static string AdvanceOpenTrunkMenu {
            get {
                return ResourceManager.GetString("AdvanceOpenTrunkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده سرعت خودرو.
        /// </summary>
        internal static string AdvanceRequestSpeedMenu {
            get {
                return ResourceManager.GetString("AdvanceRequestSpeedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شنود.
        /// </summary>
        internal static string AdvanceRequestVoiceMenu {
            get {
                return ResourceManager.GetString("AdvanceRequestVoiceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استارت هوشمند.
        /// </summary>
        internal static string AdvanceStartMenu {
            get {
                return ResourceManager.GetString("AdvanceStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وضعیت:.
        /// </summary>
        internal static string CarDateLabel {
            get {
                return ResourceManager.GetString("CarDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سویچ باز است.
        /// </summary>
        internal static string CarStatusOpen {
            get {
                return ResourceManager.GetString("CarStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی خودرو.
        /// </summary>
        internal static string DisplayAlertAlertCar {
            get {
                return ResourceManager.GetString("DisplayAlertAlertCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        internal static string DisplayAlertAlertCarFirst {
            get {
                return ResourceManager.GetString("DisplayAlertAlertCarFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertAlertCarSecond {
            get {
                return ResourceManager.GetString("DisplayAlertAlertCarSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DisplayAlertAlertCarthird {
            get {
                return ResourceManager.GetString("DisplayAlertAlertCarthird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قفل کودک.
        /// </summary>
        internal static string DisplayAlertChildLock {
            get {
                return ResourceManager.GetString("DisplayAlertChildLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال شود.
        /// </summary>
        internal static string DisplayAlertChildLockFirst {
            get {
                return ResourceManager.GetString("DisplayAlertChildLockFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال شود.
        /// </summary>
        internal static string DisplayAlertChildLockSecond {
            get {
                return ResourceManager.GetString("DisplayAlertChildLockSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertChildLockthird {
            get {
                return ResourceManager.GetString("DisplayAlertChildLockthird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قفل دربها و مسلح کردن دزدگیر.
        /// </summary>
        internal static string DisplayAlertClose {
            get {
                return ResourceManager.GetString("DisplayAlertClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بصورت با صدا.
        /// </summary>
        internal static string DisplayAlertCloseFirst {
            get {
                return ResourceManager.GetString("DisplayAlertCloseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بصورت بی صدا.
        /// </summary>
        internal static string DisplayAlertCloseSecond {
            get {
                return ResourceManager.GetString("DisplayAlertCloseSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertClosethird {
            get {
                return ResourceManager.GetString("DisplayAlertClosethird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموش کردن موتور.
        /// </summary>
        internal static string DisplayAlertForceStop {
            get {
                return ResourceManager.GetString("DisplayAlertForceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموش کردن ماشین.
        /// </summary>
        internal static string DisplayAlertForceStopFirst {
            get {
                return ResourceManager.GetString("DisplayAlertForceStopFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو خاموشی ماشین.
        /// </summary>
        internal static string DisplayAlertForceStopSecond {
            get {
                return ResourceManager.GetString("DisplayAlertForceStopSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertForceStopthird {
            get {
                return ResourceManager.GetString("DisplayAlertForceStopthird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت موقعیت خودرو.
        /// </summary>
        internal static string DisplayAlertLocation {
            get {
                return ResourceManager.GetString("DisplayAlertLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت موقعیت ازطریق GPS.
        /// </summary>
        internal static string DisplayAlertLocationFirst {
            get {
                return ResourceManager.GetString("DisplayAlertLocationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت محدوده ماشین.
        /// </summary>
        internal static string DisplayAlertLocationSecond {
            get {
                return ResourceManager.GetString("DisplayAlertLocationSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertLocationThird {
            get {
                return ResourceManager.GetString("DisplayAlertLocationThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن دربها و غیر مسلح کردن دزدگیر.
        /// </summary>
        internal static string DisplayAlertOpen {
            get {
                return ResourceManager.GetString("DisplayAlertOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بصورت با صدا.
        /// </summary>
        internal static string DisplayAlertOpenFirst {
            get {
                return ResourceManager.GetString("DisplayAlertOpenFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بصورت بی صدا.
        /// </summary>
        internal static string DisplayAlertOpenSecond {
            get {
                return ResourceManager.GetString("DisplayAlertOpenSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertOpenthird {
            get {
                return ResourceManager.GetString("DisplayAlertOpenthird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن درب صندق عقب.
        /// </summary>
        internal static string DisplayAlertTrunk {
            get {
                return ResourceManager.GetString("DisplayAlertTrunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط صندوق.
        /// </summary>
        internal static string DisplayAlertTrunkFirst {
            get {
                return ResourceManager.GetString("DisplayAlertTrunkFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق+غیر مسلح.
        /// </summary>
        internal static string DisplayAlertTrunkSecond {
            get {
                return ResourceManager.GetString("DisplayAlertTrunkSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertTrunkthird {
            get {
                return ResourceManager.GetString("DisplayAlertTrunkthird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن پنجره‌ها.
        /// </summary>
        internal static string DisplayAlertWindows {
            get {
                return ResourceManager.GetString("DisplayAlertWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        internal static string DisplayAlertWindowsFirst {
            get {
                return ResourceManager.GetString("DisplayAlertWindowsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string DisplayAlertWindowsSecond {
            get {
                return ResourceManager.GetString("DisplayAlertWindowsSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DisplayAlertWindowsthird {
            get {
                return ResourceManager.GetString("DisplayAlertWindowsthird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کد.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل خود را وارد کنید.
        /// </summary>
        internal static string LoginDetails {
            get {
                return ResourceManager.GetString("LoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        internal static string LoginEntry {
            get {
                return ResourceManager.GetString("LoginEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به اپلیکیشن HY MAX خوش آمدید.
        /// </summary>
        internal static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string LoginVerifyButton {
            get {
                return ResourceManager.GetString("LoginVerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ۶ رقمی به شماره شما پیامک شد.
        /// </summary>
        internal static string LoginVerifyDetails {
            get {
                return ResourceManager.GetString("LoginVerifyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسالی را وارد کنید.
        /// </summary>
        internal static string LoginVerifyHeader {
            get {
                return ResourceManager.GetString("LoginVerifyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامکی دریافت نکردید؟.
        /// </summary>
        internal static string LoginVerifySendSMS {
            get {
                return ResourceManager.GetString("LoginVerifySendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مجدد پیامک.
        /// </summary>
        internal static string LoginVerifySendSMSButton {
            get {
                return ResourceManager.GetString("LoginVerifySendSMSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودروها.
        /// </summary>
        internal static string MainCarButton {
            get {
                return ResourceManager.GetString("MainCarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفته.
        /// </summary>
        internal static string MainMoreButton {
            get {
                return ResourceManager.GetString("MainMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش‌گیری.
        /// </summary>
        internal static string MainReportButton {
            get {
                return ResourceManager.GetString("MainReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        internal static string MainSettingsButton {
            get {
                return ResourceManager.GetString("MainSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اثر انگشت خود را وارد کنید.
        /// </summary>
        internal static string PutFinger {
            get {
                return ResourceManager.GetString("PutFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اثر انگشت خود را وارد کنید.
        /// </summary>
        internal static string PutFingerHeader {
            get {
                return ResourceManager.GetString("PutFingerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش امنیت ورود به نرم افزار را انتخاب کنید.
        /// </summary>
        internal static string SecureDetails {
            get {
                return ResourceManager.GetString("SecureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اثر انگشت.
        /// </summary>
        internal static string SecureFinger {
            get {
                return ResourceManager.GetString("SecureFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امنیت ورود به HY MAX.
        /// </summary>
        internal static string SecureHeader {
            get {
                return ResourceManager.GetString("SecureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        internal static string SecurePassword {
            get {
                return ResourceManager.GetString("SecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگو.
        /// </summary>
        internal static string SecurePattern {
            get {
                return ResourceManager.GetString("SecurePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پین کد.
        /// </summary>
        internal static string SecurePin {
            get {
                return ResourceManager.GetString("SecurePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اثر انگشت را وارد کنید.
        /// </summary>
        internal static string SetSecureDetailsFingerPrint {
            get {
                return ResourceManager.GetString("SetSecureDetailsFingerPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا رمز عبور را وارد کنید.
        /// </summary>
        internal static string SetSecureDetailsPassword {
            get {
                return ResourceManager.GetString("SetSecureDetailsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا الگو مورد نظر را انتخاب کنید.
        /// </summary>
        internal static string SetSecureDetailsPattern {
            get {
                return ResourceManager.GetString("SetSecureDetailsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا پین کد را وارد کنید.
        /// </summary>
        internal static string SetSecureDetailsPin {
            get {
                return ResourceManager.GetString("SetSecureDetailsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره نرم افزار.
        /// </summary>
        internal static string SettingsAboutMenu {
            get {
                return ResourceManager.GetString("SettingsAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاتالوگ دستگاه.
        /// </summary>
        internal static string SettingsCatalogeMenu {
            get {
                return ResourceManager.GetString("SettingsCatalogeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه ردیابی.
        /// </summary>
        internal static string SettingsOpenwebMenu {
            get {
                return ResourceManager.GetString("SettingsOpenwebMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        internal static string SettingsSupportMenu {
            get {
                return ResourceManager.GetString("SettingsSupportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات کاربری.
        /// </summary>
        internal static string SettingsUsersMenu {
            get {
                return ResourceManager.GetString("SettingsUsersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورژن دستگاه.
        /// </summary>
        internal static string SettingsVersionMenu {
            get {
                return ResourceManager.GetString("SettingsVersionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودروتو هروقت و هرجا کنترل کن.
        /// </summary>
        internal static string Welcome1Description {
            get {
                return ResourceManager.GetString("Welcome1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودروتو کنترل کن.
        /// </summary>
        internal static string Welcome1Header {
            get {
                return ResourceManager.GetString("Welcome1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر تعداد خوردویی که دوس داری رو ردیابی کن.
        /// </summary>
        internal static string Welcome2Description {
            get {
                return ResourceManager.GetString("Welcome2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی از ردیابی چندین خودرو.
        /// </summary>
        internal static string Welcome2Header {
            get {
                return ResourceManager.GetString("Welcome2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در لحظه خودروتو ردیابی کن.
        /// </summary>
        internal static string Welcome3Description {
            get {
                return ResourceManager.GetString("Welcome3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیابی آنلاین.
        /// </summary>
        internal static string Welcome3Header {
            get {
                return ResourceManager.GetString("Welcome3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        internal static string WelcomeButton {
            get {
                return ResourceManager.GetString("WelcomeButton", resourceCulture);
            }
        }
    }
}
